#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
USE_PROCD=1

DIR=/etc/nftclash
CLASH_HOME_DIR=$DIR/clash

start_service() {
	$DIR/service.sh init_startup || return 1
	$DIR/service.sh init_started
	SAFE_PATHS=$(cat "$DIR/env/SAFE_PATHS")
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 0
	procd_set_param stdout 0
	procd_set_param env SAFE_PATHS=$SAFE_PATHS
	procd_set_param command $CLASH_HOME_DIR/clash -d $CLASH_HOME_DIR
	procd_set_param user nftclash
	procd_close_instance
	# Connection Checks
	procd_open_instance
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command $DIR/service.sh conn_check -nocolor
	procd_close_instance
	# Init Checcks
	procd_open_instance
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command $DIR/service.sh init_check -nocolor
	procd_close_instance
}

stop_service() {
	$DIR/service.sh flush_fw
}

reload_service() {
	$DIR/service.sh reinit_fw
}
