#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
USE_PROCD=1

DIR=/etc/nftclash
CLASH_HOME_DIR=$DIR/clash

extra_command "flush_fw" "Flush firewall rules"
extra_command "reload_fw" "Reinit firewall rules"
extra_command "reload_clash" "Reload clash config"
extra_command "update_clash" "Update clash config"
extra_command "check_update" "Check service update"

start_service() {
	$DIR/service.sh init_startup || return 1
	$DIR/service.sh init_started || return 1
	ENV_DISABLE_EMBED_CA=$(cat "$DIR/env/DISABLE_EMBED_CA")
	ENV_DISABLE_SYSTEM_CA=$(cat "$DIR/env/DISABLE_SYSTEM_CA")
	ENV_DISABLE_LOOPBACK_DETECTOR=$(cat "$DIR/env/DISABLE_LOOPBACK_DETECTOR")
	ENV_SKIP_SYSTEM_IPV6_CHECK=$(cat "$DIR/env/SKIP_SYSTEM_IPV6_CHECK")
	ENV_SKIP_SAFE_PATH_CHECK=$(cat "$DIR/env/SKIP_SAFE_PATH_CHECK")
	ENV_SAFE_PATHS=$(cat "$DIR/env/SAFE_PATHS")
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 0
	procd_set_param stdout 0
	procd_set_param env DISABLE_EMBED_CA=$ENV_DISABLE_EMBED_CA \
											DISABLE_SYSTEM_CA=$ENV_DISABLE_SYSTEM_CA \
											DISABLE_LOOPBACK_DETECTOR=$ENV_DISABLE_LOOPBACK_DETECTOR \
											SKIP_SYSTEM_IPV6_CHECK=$ENV_SKIP_SYSTEM_IPV6_CHECK \
											SKIP_SAFE_PATH_CHECK=$ENV_SKIP_SAFE_PATH_CHECK \
											SAFE_PATHS=$ENV_SAFE_PATHS \
											DISABLE_NFTABLES=1
	procd_set_param command $CLASH_HOME_DIR/clash -d $CLASH_HOME_DIR
	procd_set_param user nftclash
	procd_close_instance
	# Connection Checks
	procd_open_instance
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param command $DIR/service.sh init_conn_check
	procd_close_instance
}

stop_service() {
	$DIR/service.sh flush_fw
}

reload_service() {
	$DIR/service.sh reinit_fw
	$DIR/service.sh reload_clash_config
}

# Extra Commands

flush_fw() {
	$DIR/service.sh flush_fw
}

reload_fw() {
	$DIR/service.sh reinit_fw
}

reload_clash() {
	$DIR/service.sh reload_clash_config
}

update_clash() {
	$DIR/service.sh update_clash_config
}

check_update() {
	$DIR/service.sh check_update
}
